api = 2
core = 7.x

; Contributed modules.
projects[file_entity][type] = "module"
projects[file_entity][subdir] = "contrib"
projects[file_entity][version] = "2.0-alpha2"
projects[file_lock][type] = "module"
projects[file_lock][subdir] = "contrib"
projects[file_lock][version] = "2.x-dev"
projects[filefield_paths][type] = "module"
projects[filefield_paths][subdir] = "contrib"
projects[filefield_paths][version] = "1.0-beta4"
projects[filefield_sources][type] = "module"
projects[filefield_sources][subdir] = "contrib"
projects[filefield_sources][version] = "1.8"
projects[filefield_sources_plupload][type] = "module"
projects[filefield_sources_plupload][subdir] = "contrib"
projects[filefield_sources_plupload][version] = "1.1"
